services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: hakuvahti
    ports:
      - "27017:27017"
    networks:
      - internal

  app:
    user: root
    build:
      context: .
      dockerfile: openshift/Dockerfile
      target: development
    hostname: hakuvahti
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - type: tmpfs
        target: /app/dist
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - internal
      - stonehenge-network
    extra_hosts:
      - "helfi-rekry.docker.so:host-gateway"
      - "elastic-helfi-rekry.docker.so:host-gateway"
      - "host-machine.local:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hakuvahti-app.entrypoints=https"
      - "traefik.http.routers.hakuvahti-app.rule=Host(`hakuvahti.docker.so`)"
      - "traefik.http.routers.hakuvahti-app.tls=true"
      - "traefik.http.services.hakuvahti-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=stonehenge-network"

volumes:
  node_modules:

networks:
  internal:
    internal: true
  stonehenge-network:
    external: true
