services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: hakuvahti
    ports:
      - "27017:27017"
    networks:
      - hav-internal
      - helfi-hakuvahti-network

  nodejs:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app-root/src:delegated
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - hav-internal
      - helfi-hakuvahti-network
    extra_hosts:
      - "helfi-rekry.docker.so:host-gateway"
      - "elastic-helfi-rekry.docker.so:host-gateway"
      - "host-machine.local:host-gateway"

networks:
  hav-internal:
    internal: true
  helfi-hakuvahti-network:
    driver: bridge
