version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: hakuvahti
    ports:
      - "27017:27017"
    networks:
      - hav-internal


  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - hav-internal
      - hav-network

networks:
  hav-internal:
    internal: true
  hav-network:
    driver: bridge