sonar.projectKey=City-of-Helsinki_helfi-hakuvahti
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.inclusions=**/*.ts,openshift/Dockerfile
sonar.exclusions=test/**/*,src/bin/*test*,src/bin/hav-fix-employment-arrays.ts,src/bin/hav-migrate-site-id.ts,src/bin/hav-update-schema.ts,src/bin/hav-update-subscription-length.ts
sonar.test.inclusions=test/**/*.ts
