sonar.projectKey=City-of-Helsinki_helfi-hakuvahti
sonar.organization=city-of-helsinki
sonar.inclusions=**/*.ts,Dockerfile,openshift/Dockerfile
sonar.exclusions=test/**/*
sonar.test.inclusions=test/**/*.ts
