sonar.projectKey=City-of-Helsinki_helfi-hakuvahti
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.inclusions=**/*.ts,openshift/Dockerfile
sonar.exclusions=test/**/*
sonar.coverage.exclusions=src/bin/*test*,src/bin/hav-update-subscription-length.ts,src/bin/hav-test-all-templates.ts
sonar.test.inclusions=test/**/*.ts
