on:
  pull_request:
  push:
    branches: ['main', 'dev']
name: CI
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: druidfi/stonehenge

      - name: Install and start Stonehenge
        run: make up

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Start hakuvahti
        run: make fresh

      - name: Lint
        run: docker compose exec app bash -c "npx biome ci src --reporter=github --colors=off"

      - name: Run tests
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: NPM Audit
        run: docker compose exec app bash -c "npm audit"
